CREATE TABLE GYARTO
(adoszam INT NOT NULL,
nev VARCHAR(30) NOT NULL,
telephely VARCHAR(50) NOT NULL,
irsz VARCHAR(4) NOT NULL,
varos VARCHAR(40) NOT NULL,
utca VARCHAR(100) NOT NULL,
PRIMARY KEY (adoszam));

CREATE TABLE TERMEK
(tkod INT NOT NULL,
nev VARCHAR(50) NOT NULL,
ear INT CHECK (ear > 0) NOT NULL,
gyarto INT NOT NULL,
PRIMARY KEY (tkod),
FOREIGN KEY (gyarto) REFERENCES GYARTO(adoszam));

CREATE TABLE Egysegek
(aru INT NOT NULL,
db INT CHECK (db > 0) NOT NULL,
FOREIGN KEY (aru) REFERENCES TERMEK(tkod));

CREATE TABLE Alkatresz
(akod INT NOT NULL,
nev VARCHAR(50) NOT NULL,
PRIMARY KEY (akod));

CREATE TABLE Komponens
(termek INT NOT NULL,
alkatresz INT NOT NULL,
FOREIGN KEY (termek) REFERENCES TERMEK(tkod),
FOREIGN KEY (alkatresz) REFERENCES Alkatresz(akod));