CREATE TABLE GYARTO 
(adoszam INT NOT NULL,
nev VARCHAR(30) NOT NULL,
telephely VARCHAR(50) NOT NULL,
PRIMARY KEY (adoszam));

CREATE TABLE TERMEK
(tkod INT NOT NULL,
nev VARCHAR(50) NOT NULL,
ear INT CHECK(ear > 0),
gyarto INT NOT NULL,
PRIMARY KEY (tkod),
FOREIGN KEY(gyarto) REFERENCES GYARTO(adoszam));
