CREATE TABLE KONYV
(isbn VARCHAR(20) NOT NULL,
cim VARCHAR(40) NOT NULL,
targy VARCHAR(30) NOT NULL,
ar INT NOT NULL,
PRIMARY KEY (isbn));

SELECT count(isbn) FROM KONYV;
SELECT avg(ar) FROM KONYV;
SELECT min(ar) FROM KONYV;
SELECT count(targy) FROM KONYV WHERE targy='AB';
SELECT max(ar) FROM KONYV WHERE targy='AB';
SELECT cim FROM KONYV WHERE ar > (SELECT avg(ar) FROM KONYV);
SELECT count(isbn) FROM KONYV WHERE ar > (SELECT avg(ar) FROM KONYV);